### ISSUE TITLE
No longer working in Chrome

### ISSUE THREAD

**Issue by pcb1962** [grantwinney/hide-google-doodles#24]
Google changed something this week so doodles appear in places they didn't used to.
Unfortunately it seems that the change has broken this extension.

**Comment by grantwinney** [comment]
Are you looking at a tab that has google.com loaded in it (like the first image), or just at the new tab page (the second image)?

Because I can't block it on the new tab page, but [there is a workaround](https://github.com/grantwinney/hide-google-doodles#hiding-on-the-new-tab).

![image](https://user-images.githubusercontent.com/1354059/97744781-362d9f00-1abe-11eb-95c0-e0ab3fc47ddf.png)

![image](https://user-images.githubusercontent.com/1354059/97744775-33cb4500-1abe-11eb-915f-697975e35702.png)

**Comment by pcb1962** [comment]
Hi, yes sorry, I was assuming it would work on the new tab page, which I have set to google. 
It works great if I type google.com on an already open tab.
I've been using the workaround for many months, customise the page with a background, and that worked great until this week, but now I am seeing the doodle on my customised page.
Thanks for your help.

**Comment by grantwinney** [comment]
Oh, that's great. Wow, thanks for the heads up, guess that's no longer a workaround. 🙄

**Comment by grantwinney** [comment]
Just a heads up, I heard from someone else that there are redirect extensions too. So you can redirect the "new tab" page to google.com if you want, and then this extension (should I hope!) block the doodle from there.

* [New Tab Redirect - Chrome Web Store](https://chrome.google.com/webstore/detail/new-tab-redirect/icpgjfneehieebagbmdbhnlpiopdcmna)
* [New Tab Changer - Chrome Web Store](https://chrome.google.com/webstore/detail/new-tab-changer/occbjkhimchkolibngmcefpjlbknggfh)
